
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 51;
  public static final int IDENTIFIER = 86;
  public static final int FROM = 50;
  public static final int GT = 68;
  public static final int ARROW = 74;
  public static final int TYPEOF = 29;
  public static final int IMPLEMENTS = 39;
  public static final int CONST = 6;
  public static final int INT_LITERAL = 87;
  public static final int ASYNC = 45;
  public static final int EXPORT = 13;
  public static final int EXP = 57;
  public static final int GET = 47;
  public static final int GEQ = 70;
  public static final int CONSTRUCTOR = 49;
  public static final int ENUM = 37;
  public static final int RBRACK = 79;
  public static final int COMMA = 83;
  public static final int CATCH = 4;
  public static final int RBRACE = 81;
  public static final int THROW = 27;
  public static final int RPAREN = 77;
  public static final int LBRACK = 78;
  public static final int LT = 67;
  public static final int LBRACE = 80;
  public static final int LPAREN = 76;
  public static final int YIELD = 34;
  public static final int PROTECTED = 43;
  public static final int NOT = 73;
  public static final int VAR = 30;
  public static final int PACKAGE = 41;
  public static final int EQ = 63;
  public static final int UNDEFINED_LITERAL = 93;
  public static final int BOOLEAN_LITERAL = 91;
  public static final int MOD = 56;
  public static final int CLASS = 5;
  public static final int SUPER = 24;
  public static final int PLUS = 52;
  public static final int QUESTION = 75;
  public static final int WHILE = 32;
  public static final int EXTENDS = 14;
  public static final int DELETE = 10;
  public static final int ASSIGN = 58;
  public static final int INTERFACE = 40;
  public static final int SWITCH = 25;
  public static final int DO = 11;
  public static final int FOR = 16;
  public static final int MINUS_ASSIGN = 60;
  public static final int VOID = 31;
  public static final int DIV = 55;
  public static final int PUBLIC = 44;
  public static final int RETURN = 23;
  public static final int MULT = 54;
  public static final int ELSE = 12;
  public static final int TRY = 28;
  public static final int EXACT_EQ = 65;
  public static final int BREAK = 2;
  public static final int DOT = 84;
  public static final int NULL_LITERAL = 92;
  public static final int STRING_LITERAL = 89;
  public static final int SEMICOLON = 82;
  public static final int EOF = 0;
  public static final int MULT_ASSIGN = 61;
  public static final int THIS = 26;
  public static final int DEFAULT = 9;
  public static final int FUNCTION = 17;
  public static final int AWAIT = 38;
  public static final int IMPORT = 19;
  public static final int MINUS = 53;
  public static final int FLOAT_LITERAL = 88;
  public static final int DEBUGGER = 8;
  public static final int IN = 20;
  public static final int OR = 72;
  public static final int SET = 48;
  public static final int error = 1;
  public static final int FINALLY = 15;
  public static final int CONTINUE = 7;
  public static final int IF = 18;
  public static final int INSTANCEOF = 21;
  public static final int DIV_ASSIGN = 62;
  public static final int OF = 46;
  public static final int PLUS_ASSIGN = 59;
  public static final int COLON = 85;
  public static final int EXACT_NEQ = 66;
  public static final int CASE = 3;
  public static final int NEW = 22;
  public static final int NEQ = 64;
  public static final int TEMPLATE_LITERAL = 90;
  public static final int AND = 71;
  public static final int PRIVATE = 42;
  public static final int STATIC = 36;
  public static final int LET = 35;
  public static final int WITH = 33;
  public static final int LEQ = 69;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BREAK",
  "CASE",
  "CATCH",
  "CLASS",
  "CONST",
  "CONTINUE",
  "DEBUGGER",
  "DEFAULT",
  "DELETE",
  "DO",
  "ELSE",
  "EXPORT",
  "EXTENDS",
  "FINALLY",
  "FOR",
  "FUNCTION",
  "IF",
  "IMPORT",
  "IN",
  "INSTANCEOF",
  "NEW",
  "RETURN",
  "SUPER",
  "SWITCH",
  "THIS",
  "THROW",
  "TRY",
  "TYPEOF",
  "VAR",
  "VOID",
  "WHILE",
  "WITH",
  "YIELD",
  "LET",
  "STATIC",
  "ENUM",
  "AWAIT",
  "IMPLEMENTS",
  "INTERFACE",
  "PACKAGE",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "ASYNC",
  "OF",
  "GET",
  "SET",
  "CONSTRUCTOR",
  "FROM",
  "AS",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "EXP",
  "ASSIGN",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "MULT_ASSIGN",
  "DIV_ASSIGN",
  "EQ",
  "NEQ",
  "EXACT_EQ",
  "EXACT_NEQ",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "AND",
  "OR",
  "NOT",
  "ARROW",
  "QUESTION",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "COLON",
  "IDENTIFIER",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "TEMPLATE_LITERAL",
  "BOOLEAN_LITERAL",
  "NULL_LITERAL",
  "UNDEFINED_LITERAL"
  };
}

