
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act6;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserAct6 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserAct6() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserAct6(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserAct6(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\035\000\002\002\004\000\002\002\003\000\002\003" +
    "\011\000\002\004\004\000\002\004\002\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\004\000" +
    "\002\006\007\000\002\007\003\000\002\007\005\000\002" +
    "\010\007\000\002\011\003\000\002\011\005\000\002\012" +
    "\003\000\002\012\003\000\002\013\006\000\002\014\005" +
    "\000\002\014\005\000\002\014\005\000\002\014\005\000" +
    "\002\014\005\000\002\014\005\000\002\014\005\000\002" +
    "\014\004\000\002\014\005\000\002\014\003\000\002\014" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\004\004\005\001\002\000\004\002\000\001" +
    "\002\000\004\026\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\020\011\001\002\000" +
    "\004\021\012\001\002\000\004\022\013\001\002\000\014" +
    "\003\ufffd\005\ufffd\006\ufffd\023\ufffd\026\ufffd\001\002\000" +
    "\014\003\023\005\022\006\020\023\015\026\025\001\002" +
    "\000\004\002\uffff\001\002\000\014\003\ufffe\005\ufffe\006" +
    "\ufffe\023\ufffe\026\ufffe\001\002\000\014\003\ufffc\005\ufffc" +
    "\006\ufffc\023\ufffc\026\ufffc\001\002\000\004\020\066\001" +
    "\002\000\014\003\ufffa\005\ufffa\006\ufffa\023\ufffa\026\ufffa" +
    "\001\002\000\004\020\057\001\002\000\004\024\056\001" +
    "\002\000\014\003\ufffb\005\ufffb\006\ufffb\023\ufffb\026\ufffb" +
    "\001\002\000\004\007\026\001\002\000\012\017\027\020" +
    "\032\026\030\027\031\001\002\000\012\017\027\020\032" +
    "\026\030\027\031\001\002\000\026\010\uffe6\011\uffe6\012" +
    "\uffe6\013\uffe6\014\uffe6\015\uffe6\016\uffe6\021\uffe6\024\uffe6" +
    "\025\uffe6\001\002\000\026\010\uffe5\011\uffe5\012\uffe5\013" +
    "\uffe5\014\uffe5\015\uffe5\016\uffe5\021\uffe5\024\uffe5\025\uffe5" +
    "\001\002\000\012\017\027\020\032\026\030\027\031\001" +
    "\002\000\022\010\035\011\041\012\042\013\040\014\034" +
    "\015\036\016\043\024\037\001\002\000\012\017\027\020" +
    "\032\026\030\027\031\001\002\000\012\017\027\020\032" +
    "\026\030\027\031\001\002\000\012\017\027\020\032\026" +
    "\030\027\031\001\002\000\014\003\ufff0\005\ufff0\006\ufff0" +
    "\023\ufff0\026\ufff0\001\002\000\012\017\027\020\032\026" +
    "\030\027\031\001\002\000\012\017\027\020\032\026\030" +
    "\027\031\001\002\000\012\017\027\020\032\026\030\027" +
    "\031\001\002\000\012\017\027\020\032\026\030\027\031" +
    "\001\002\000\026\010\035\011\041\012\042\013\040\014" +
    "\034\015\036\016\uffe9\021\uffe9\024\uffe9\025\uffe9\001\002" +
    "\000\026\010\uffed\011\uffed\012\uffed\013\uffed\014\uffed\015" +
    "\uffed\016\uffed\021\uffed\024\uffed\025\uffed\001\002\000\026" +
    "\010\uffee\011\uffee\012\042\013\040\014\034\015\uffee\016" +
    "\uffee\021\uffee\024\uffee\025\uffee\001\002\000\026\010\uffec" +
    "\011\uffec\012\uffec\013\uffec\014\uffec\015\uffec\016\uffec\021" +
    "\uffec\024\uffec\025\uffec\001\002\000\026\010\035\011\041" +
    "\012\042\013\040\014\034\015\uffea\016\uffea\021\uffea\024" +
    "\uffea\025\uffea\001\002\000\026\010\uffef\011\uffef\012\042" +
    "\013\040\014\034\015\uffef\016\uffef\021\uffef\024\uffef\025" +
    "\uffef\001\002\000\026\010\uffeb\011\uffeb\012\uffeb\013\uffeb" +
    "\014\uffeb\015\uffeb\016\uffeb\021\uffeb\024\uffeb\025\uffeb\001" +
    "\002\000\022\010\035\011\041\012\042\013\040\014\034" +
    "\015\036\016\043\021\054\001\002\000\026\010\uffe7\011" +
    "\uffe7\012\uffe7\013\uffe7\014\uffe7\015\uffe7\016\uffe7\021\uffe7" +
    "\024\uffe7\025\uffe7\001\002\000\026\010\uffe8\011\uffe8\012" +
    "\uffe8\013\uffe8\014\uffe8\015\uffe8\016\uffe8\021\uffe8\024\uffe8" +
    "\025\uffe8\001\002\000\014\003\ufff9\005\ufff9\006\ufff9\023" +
    "\ufff9\026\ufff9\001\002\000\004\026\061\001\002\000\006" +
    "\021\063\025\062\001\002\000\006\021\ufff7\025\ufff7\001" +
    "\002\000\004\026\065\001\002\000\004\024\064\001\002" +
    "\000\014\003\ufff8\005\ufff8\006\ufff8\023\ufff8\026\ufff8\001" +
    "\002\000\006\021\ufff6\025\ufff6\001\002\000\014\017\027" +
    "\020\032\026\030\027\031\030\071\001\002\000\006\021" +
    "\ufff4\025\ufff4\001\002\000\006\021\074\025\073\001\002" +
    "\000\006\021\ufff2\025\ufff2\001\002\000\024\010\035\011" +
    "\041\012\042\013\040\014\034\015\036\016\043\021\ufff1" +
    "\025\ufff1\001\002\000\014\017\027\020\032\026\030\027" +
    "\031\030\071\001\002\000\004\024\075\001\002\000\014" +
    "\003\ufff5\005\ufff5\006\ufff5\023\ufff5\026\ufff5\001\002\000" +
    "\006\021\ufff3\025\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\074\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\013\001\001\000\012\005\015\006\016\010\023" +
    "\013\020\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\032\001\001\000\004\014\054\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\052\001" +
    "\001\000\002\001\001\000\004\014\051\001\001\000\004" +
    "\014\050\001\001\000\004\014\047\001\001\000\002\001" +
    "\001\000\004\014\046\001\001\000\004\014\045\001\001" +
    "\000\004\014\044\001\001\000\004\014\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\011\067\012" +
    "\066\014\071\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\012\075\014" +
    "\071\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserAct6$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserAct6$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserAct6$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private boolean huboError = false;

    public void syntax_error(Symbol s) {
        huboError = true;
        int linea = s.left;
        int columna = s.right;
        System.err.println("-> [ERROR SINTÁCTICO] Línea: " + linea + ", Columna: " + columna + " | Causa/Token no esperado: '" + s.value + "'");
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        System.err.println("-> [ERROR FATAL] Imposible continuar en Línea: " + s.left + ", Columna: " + s.right);
    }

    public boolean huboErrorFatal() {
        return huboError;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserAct6$actions {
  private final ParserAct6 parser;

  /** Constructor */
  CUP$ParserAct6$actions(ParserAct6 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserAct6$do_action_part00000000(
    int                        CUP$ParserAct6$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct6$parser,
    java.util.Stack            CUP$ParserAct6$stack,
    int                        CUP$ParserAct6$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserAct6$result;

      /* select the action based on the action number */
      switch (CUP$ParserAct6$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)).value;
		RESULT = start_val;
              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserAct6$parser.done_parsing();
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= metodo 
            {
              Object RESULT =null;
		 
    System.out.println("Regla reconocida: inicio"); 

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // metodo ::= FUNCTION IDENTIFICADOR PAR_IZQ PAR_DER LLAVE_IZQ cuerpo_metodo LLAVE_DER 
            {
              Object RESULT =null;
		 
    System.out.println("Regla reconocida: metodo"); 

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("metodo",1, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-6)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cuerpo_metodo ::= cuerpo_metodo sentencia 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("cuerpo_metodo",2, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // cuerpo_metodo ::= 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("cuerpo_metodo",2, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= lectura 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= escritura 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 
                System.out.println("-> Recuperación sintáctica exitosa: sentencia descartada hasta ';'."); 
            
              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("sentencia",3, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lectura ::= LEER PAR_IZQ lista_identificadores PAR_DER PUNTO_COMA 
            {
              Object RESULT =null;
		 
    System.out.println("Regla reconocida: lectura"); 

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("lectura",4, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_identificadores ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("lista_identificadores",5, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_identificadores ::= lista_identificadores COMA IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("lista_identificadores",5, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // escritura ::= ESCRIBIR PAR_IZQ lista_elementos PAR_DER PUNTO_COMA 
            {
              Object RESULT =null;
		 
    System.out.println("Regla reconocida: escritura"); 

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("escritura",6, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_elementos ::= elemento 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("lista_elementos",7, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_elementos ::= lista_elementos COMA elemento 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("lista_elementos",7, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // elemento ::= CADENA 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("elemento",8, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // elemento ::= expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("elemento",8, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // asignacion ::= IDENTIFICADOR IGUAL expresion PUNTO_COMA 
            {
              Object RESULT =null;
		 
    System.out.println("Regla reconocida: asignacion"); 

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("asignacion",9, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion ::= expresion MAS expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion ::= expresion MENOS expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion ::= expresion POR expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion ::= expresion ENTRE expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion ::= expresion MOD expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= expresion AND expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= NOT expresion 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= PAR_IZQ expresion PAR_DER 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.elementAt(CUP$ParserAct6$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= VALOR 
            {
              Object RESULT =null;

              CUP$ParserAct6$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct6$stack.peek()), RESULT);
            }
          return CUP$ParserAct6$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserAct6$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserAct6$do_action(
    int                        CUP$ParserAct6$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct6$parser,
    java.util.Stack            CUP$ParserAct6$stack,
    int                        CUP$ParserAct6$top)
    throws java.lang.Exception
    {
              return CUP$ParserAct6$do_action_part00000000(
                               CUP$ParserAct6$act_num,
                               CUP$ParserAct6$parser,
                               CUP$ParserAct6$stack,
                               CUP$ParserAct6$top);
    }
}

}
