
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act6;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 10;
  public static final int MENOS = 7;
  public static final int AND = 11;
  public static final int ENTRE = 9;
  public static final int CADENA = 22;
  public static final int OR = 12;
  public static final int IGUAL = 5;
  public static final int LEER = 3;
  public static final int NOT = 13;
  public static final int FUNCTION = 2;
  public static final int POR = 8;
  public static final int COMA = 19;
  public static final int EOF = 0;
  public static final int PAR_IZQ = 14;
  public static final int ESCRIBIR = 4;
  public static final int error = 1;
  public static final int PAR_DER = 15;
  public static final int IDENTIFICADOR = 20;
  public static final int LLAVE_IZQ = 16;
  public static final int PUNTO_COMA = 18;
  public static final int LLAVE_DER = 17;
  public static final int VALOR = 21;
  public static final int MAS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "LEER",
  "ESCRIBIR",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "PAR_IZQ",
  "PAR_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "PUNTO_COMA",
  "COMA",
  "IDENTIFICADOR",
  "VALOR",
  "CADENA"
  };
}

