
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act5;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserAct5 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserAct5() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserAct5(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserAct5(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\050\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\003\005" +
    "\000\002\004\004\000\002\004\003\000\002\005\005\000" +
    "\002\005\007\000\002\007\003\000\002\007\005\000\002" +
    "\006\007\000\002\006\006\000\002\006\010\000\002\006" +
    "\007\000\002\010\004\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\004\000\002\014\005\000" +
    "\002\014\007\000\002\014\006\000\002\016\005\000\002" +
    "\016\003\000\002\015\010\000\002\015\006\000\002\012" +
    "\003\000\002\012\003\000\002\012\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\003\000\002\012\003\000" +
    "\002\013\003\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\012\004\005\005\013\006\004\007\014\001" +
    "\002\000\004\007\106\001\002\000\004\026\066\001\002" +
    "\000\004\002\102\001\002\000\004\002\ufffd\001\002\000" +
    "\010\005\013\006\004\007\014\001\002\000\010\005\ufffa" +
    "\006\ufffa\007\ufffa\001\002\000\010\005\013\006\004\007" +
    "\014\001\002\000\004\026\066\001\002\000\004\026\015" +
    "\001\002\000\004\024\016\001\002\000\026\003\025\010" +
    "\032\011\017\012\034\013\024\014\035\015\022\016\026" +
    "\025\021\026\033\001\002\000\004\026\uffe5\001\002\000" +
    "\026\003\uffee\010\uffee\011\uffee\012\uffee\013\uffee\014\uffee" +
    "\015\uffee\016\uffee\025\uffee\026\uffee\001\002\000\004\002" +
    "\ufff4\001\002\000\004\026\uffe1\001\002\000\026\003\uffef" +
    "\010\uffef\011\uffef\012\uffef\013\uffef\014\uffef\015\uffef\016" +
    "\uffef\025\uffef\026\uffef\001\002\000\004\026\uffe3\001\002" +
    "\000\004\017\065\001\002\000\004\026\uffe0\001\002\000" +
    "\004\026\054\001\002\000\026\003\ufff0\010\ufff0\011\ufff0" +
    "\012\ufff0\013\ufff0\014\ufff0\015\ufff0\016\ufff0\025\ufff0\026" +
    "\ufff0\001\002\000\026\003\025\010\032\011\017\012\034" +
    "\013\024\014\035\015\022\016\026\025\051\026\033\001" +
    "\002\000\020\011\017\012\034\013\024\014\035\015\022" +
    "\016\026\026\033\001\002\000\004\026\uffdf\001\002\000" +
    "\004\026\uffe4\001\002\000\004\026\uffe2\001\002\000\004" +
    "\026\037\001\002\000\006\017\040\021\041\001\002\000" +
    "\026\003\uffe6\010\uffe6\011\uffe6\012\uffe6\013\uffe6\014\uffe6" +
    "\015\uffe6\016\uffe6\025\uffe6\026\uffe6\001\002\000\014\027" +
    "\047\030\042\031\046\032\043\033\045\001\002\000\004" +
    "\017\uffdd\001\002\000\004\017\uffdb\001\002\000\004\017" +
    "\050\001\002\000\004\017\uffda\001\002\000\004\017\uffdc" +
    "\001\002\000\004\017\uffde\001\002\000\026\003\uffe7\010" +
    "\uffe7\011\uffe7\012\uffe7\013\uffe7\014\uffe7\015\uffe7\016\uffe7" +
    "\025\uffe7\026\uffe7\001\002\000\004\002\ufff2\001\002\000" +
    "\026\003\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1\014\ufff1" +
    "\015\ufff1\016\ufff1\025\ufff1\026\ufff1\001\002\000\006\017" +
    "\063\020\062\001\002\000\012\017\uffe8\020\uffe8\021\055" +
    "\026\056\001\002\000\014\027\047\030\042\031\046\032" +
    "\043\033\045\001\002\000\004\017\057\001\002\000\026" +
    "\003\uffea\010\uffea\011\uffea\012\uffea\013\uffea\014\uffea\015" +
    "\uffea\016\uffea\025\uffea\026\uffea\001\002\000\004\017\061" +
    "\001\002\000\026\003\uffeb\010\uffeb\011\uffeb\012\uffeb\013" +
    "\uffeb\014\uffeb\015\uffeb\016\uffeb\025\uffeb\026\uffeb\001\002" +
    "\000\004\026\064\001\002\000\026\003\uffec\010\uffec\011" +
    "\uffec\012\uffec\013\uffec\014\uffec\015\uffec\016\uffec\025\uffec" +
    "\026\uffec\001\002\000\006\017\uffe9\020\uffe9\001\002\000" +
    "\026\003\uffed\010\uffed\011\uffed\012\uffed\013\uffed\014\uffed" +
    "\015\uffed\016\uffed\025\uffed\026\uffed\001\002\000\006\017" +
    "\ufff7\022\ufff7\001\002\000\006\017\071\022\070\001\002" +
    "\000\006\023\072\026\073\001\002\000\010\005\ufff9\006" +
    "\ufff9\007\ufff9\001\002\000\004\017\074\001\002\000\006" +
    "\017\ufff6\022\ufff6\001\002\000\010\005\ufff8\006\ufff8\007" +
    "\ufff8\001\002\000\010\005\ufffb\006\ufffb\007\ufffb\001\002" +
    "\000\004\002\uffff\001\002\000\004\002\ufffe\001\002\000" +
    "\010\005\013\006\004\007\014\001\002\000\004\002\000" +
    "\001\002\000\004\002\001\001\002\000\006\017\105\022" +
    "\104\001\002\000\004\026\073\001\002\000\010\005\ufffc" +
    "\006\ufffc\007\ufffc\001\002\000\004\026\107\001\002\000" +
    "\004\024\110\001\002\000\026\003\025\010\032\011\017" +
    "\012\034\013\024\014\035\015\022\016\026\025\111\026" +
    "\033\001\002\000\004\002\ufff5\001\002\000\026\003\025" +
    "\010\032\011\017\012\034\013\024\014\035\015\022\016" +
    "\026\025\113\026\033\001\002\000\004\002\ufff3\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\014\002\005\003\007\004\011\005\010\006" +
    "\006\001\001\000\002\001\001\000\004\007\102\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\004\077\005" +
    "\010\006\076\001\001\000\002\001\001\000\006\005\074" +
    "\006\075\001\001\000\004\007\066\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\010\030\011\027\012\026" +
    "\014\022\015\017\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\052\001\001\000\002\001\001\000\012\011\051" +
    "\012\026\014\022\015\017\001\001\000\004\012\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\074\006\100\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\010\111\011\027" +
    "\012\026\014\022\015\017\001\001\000\002\001\001\000" +
    "\012\011\051\012\026\014\022\015\017\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserAct5$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserAct5$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserAct5$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private boolean fatal = false;

    public boolean huboErrorFatal() {
        return fatal;
    }

    @Override
    public void report_error(String message, Object info) {
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            System.out.println("Error sintáctico en línea " + s.left + ", columna " + s.right + ": se encontró '" + (s.value != null ? s.value : "#" + s.sym) + "'");
        } else {
            System.out.println("Error sintáctico: " + message);
        }
    }

    @Override
    public void report_fatal_error(String message, Object info) {
        fatal = true;
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            System.out.println("Error fatal en línea " + s.left + ", columna " + s.right + ": se encontró '" + (s.value != null ? s.value : "#" + s.sym) + "'");
        } else {
            System.out.println("Error fatal: " + message);
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserAct5$actions {
  private final ParserAct5 parser;

  /** Constructor */
  CUP$ParserAct5$actions(ParserAct5 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserAct5$do_action_part00000000(
    int                        CUP$ParserAct5$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct5$parser,
    java.util.Stack            CUP$ParserAct5$stack,
    int                        CUP$ParserAct5$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserAct5$result;

      /* select the action based on the action number */
      switch (CUP$ParserAct5$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)).value;
		RESULT = start_val;
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserAct5$parser.done_parsing();
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= declaracion_paquete lista_importaciones declaracion_clase 
            {
              Object RESULT =null;
		 System.out.println("Análisis sintáctico finalizado correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= lista_importaciones declaracion_clase 
            {
              Object RESULT =null;
		 System.out.println("Análisis sintáctico finalizado correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicio ::= declaracion_paquete declaracion_clase 
            {
              Object RESULT =null;
		 System.out.println("Análisis sintáctico finalizado correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inicio ::= declaracion_clase 
            {
              Object RESULT =null;
		 System.out.println("Análisis sintáctico finalizado correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaracion_paquete ::= PACKAGE nombre_cualificado PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Paquete reconocido correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_paquete",1, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_importaciones ::= lista_importaciones declaracion_importacion 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("lista_importaciones",2, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lista_importaciones ::= declaracion_importacion 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("lista_importaciones",2, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracion_importacion ::= IMPORT nombre_cualificado PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Importación reconocida correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_importacion",3, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion_importacion ::= IMPORT nombre_cualificado PUNTO ASTERISCO PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Importación reconocida correctamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_importacion",3, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // nombre_cualificado ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("nombre_cualificado",5, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // nombre_cualificado ::= nombre_cualificado PUNTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("nombre_cualificado",5, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracion_clase ::= PUBLIC CLASS IDENTIFICADOR LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;
		 
                       System.out.println("Clase principal reconocida correctamente");
                       System.out.println("Clase vacía");
                       System.out.println("Estructura de llaves válida");
                    
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracion_clase ::= CLASS IDENTIFICADOR LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;
		 
                       System.out.println("Clase principal reconocida correctamente");
                       System.out.println("Clase vacía");
                       System.out.println("Estructura de llaves válida");
                    
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declaracion_clase ::= PUBLIC CLASS IDENTIFICADOR LLAVE_IZQ cuerpo_clase LLAVE_DER 
            {
              Object RESULT =null;
		 
                       System.out.println("Clase principal reconocida correctamente");
                       System.out.println("Clase con miembros");
                       System.out.println("Estructura de llaves válida");
                    
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-5)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declaracion_clase ::= CLASS IDENTIFICADOR LLAVE_IZQ cuerpo_clase LLAVE_DER 
            {
              Object RESULT =null;
		 
                       System.out.println("Clase principal reconocida correctamente");
                       System.out.println("Clase con miembros");
                       System.out.println("Estructura de llaves válida");
                    
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // cuerpo_clase ::= cuerpo_clase miembro_clase 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",6, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // cuerpo_clase ::= miembro_clase 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",6, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // miembro_clase ::= declaracion_atributo 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("miembro_clase",7, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // miembro_clase ::= declaracion_constante 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("miembro_clase",7, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // miembro_clase ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("[Recuperación]: Declaración inválida recuperada en ';'"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("miembro_clase",7, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracion_atributo ::= tipo lista_identificadores PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Declaración de atributo o variable reconocida"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_atributo",10, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracion_atributo ::= tipo IDENTIFICADOR IGUAL valor PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Inicialización de variable o atributo reconocida"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_atributo",10, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracion_atributo ::= tipo IDENTIFICADOR IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error sintáctico: Falta ',' en declaración de identificadores"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_atributo",10, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lista_identificadores ::= lista_identificadores COMA IDENTIFICADOR 
            {
              Object RESULT =null;
		 System.out.println("Declaración múltiple: identificador reconocido"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("lista_identificadores",12, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lista_identificadores ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		 System.out.println("Identificador reconocido"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("lista_identificadores",12, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // declaracion_constante ::= FINAL tipo IDENTIFICADOR IGUAL valor PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Declaración de constante inicializada reconocida"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_constante",11, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-5)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // declaracion_constante ::= FINAL tipo IDENTIFICADOR PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error sintáctico: Constante debe inicializarse obligatoriamente"); 
              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("declaracion_constante",11, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.elementAt(CUP$ParserAct5$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo ::= INT 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo ::= FLOAT 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipo ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo ::= CHAR 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo ::= STRING_TIPO 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipo ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("tipo",8, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // valor ::= NUMERO_ENTERO 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("valor",9, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // valor ::= NUMERO_FLOTANTE 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("valor",9, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // valor ::= LITERAL_CADENA 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("valor",9, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // valor ::= LITERAL_CARACTER 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("valor",9, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // valor ::= VALOR_BOOLEANO 
            {
              Object RESULT =null;

              CUP$ParserAct5$result = parser.getSymbolFactory().newSymbol("valor",9, ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct5$stack.peek()), RESULT);
            }
          return CUP$ParserAct5$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserAct5$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserAct5$do_action(
    int                        CUP$ParserAct5$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct5$parser,
    java.util.Stack            CUP$ParserAct5$stack,
    int                        CUP$ParserAct5$top)
    throws java.lang.Exception
    {
              return CUP$ParserAct5$do_action_part00000000(
                               CUP$ParserAct5$act_num,
                               CUP$ParserAct5$parser,
                               CUP$ParserAct5$stack,
                               CUP$ParserAct5$top);
    }
}

}
