
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act5;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IMPORT = 3;
  public static final int PUNTO = 16;
  public static final int CLASS = 5;
  public static final int LITERAL_CARACTER = 24;
  public static final int IGUAL = 15;
  public static final int INT = 7;
  public static final int CHAR = 10;
  public static final int NUMERO_FLOTANTE = 22;
  public static final int NUMERO_ENTERO = 21;
  public static final int PUBLIC = 4;
  public static final int VALOR_BOOLEANO = 25;
  public static final int STRING_TIPO = 12;
  public static final int BOOLEAN = 11;
  public static final int COMA = 14;
  public static final int FLOAT = 8;
  public static final int ASTERISCO = 17;
  public static final int EOF = 0;
  public static final int FINAL = 6;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int LLAVE_IZQ = 18;
  public static final int PUNTO_COMA = 13;
  public static final int PACKAGE = 2;
  public static final int LLAVE_DER = 19;
  public static final int LITERAL_CADENA = 23;
  public static final int DOUBLE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "PUBLIC",
  "CLASS",
  "FINAL",
  "INT",
  "FLOAT",
  "DOUBLE",
  "CHAR",
  "BOOLEAN",
  "STRING_TIPO",
  "PUNTO_COMA",
  "COMA",
  "IGUAL",
  "PUNTO",
  "ASTERISCO",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "IDENTIFICADOR",
  "NUMERO_ENTERO",
  "NUMERO_FLOTANTE",
  "LITERAL_CADENA",
  "LITERAL_CARACTER",
  "VALOR_BOOLEANO"
  };
}

