
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act4;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserAct4 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserAct4() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserAct4(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserAct4(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\022\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\003\005" +
    "\000\002\003\005\000\002\004\004\000\002\004\003\000" +
    "\002\005\005\000\002\005\007\000\002\005\005\000\002" +
    "\006\007\000\002\006\006\000\002\006\007\000\002\006" +
    "\010\000\002\007\003\000\002\007\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\052\000\012\004\005\005\013\006\004\007\014\001" +
    "\002\000\004\007\044\001\002\000\006\003\037\015\021" +
    "\001\002\000\004\002\036\001\002\000\004\002\ufffd\001" +
    "\002\000\010\005\013\006\004\007\014\001\002\000\010" +
    "\005\ufff9\006\ufff9\007\ufff9\001\002\000\010\005\013\006" +
    "\004\007\014\001\002\000\006\003\020\015\021\001\002" +
    "\000\004\015\015\001\002\000\004\013\016\001\002\000" +
    "\004\014\017\001\002\000\004\002\ufff4\001\002\000\004" +
    "\010\030\001\002\000\006\010\ufff1\011\ufff1\001\002\000" +
    "\006\010\024\011\023\001\002\000\006\012\025\015\026" +
    "\001\002\000\010\005\ufff8\006\ufff8\007\ufff8\001\002\000" +
    "\004\010\027\001\002\000\006\010\ufff0\011\ufff0\001\002" +
    "\000\010\005\ufff7\006\ufff7\007\ufff7\001\002\000\010\005" +
    "\ufff6\006\ufff6\007\ufff6\001\002\000\010\005\ufffa\006\ufffa" +
    "\007\ufffa\001\002\000\004\002\uffff\001\002\000\004\002" +
    "\ufffe\001\002\000\010\005\013\006\004\007\014\001\002" +
    "\000\004\002\000\001\002\000\004\002\001\001\002\000" +
    "\004\010\043\001\002\000\006\010\042\011\041\001\002" +
    "\000\004\015\026\001\002\000\010\005\ufffc\006\ufffc\007" +
    "\ufffc\001\002\000\010\005\ufffb\006\ufffb\007\ufffb\001\002" +
    "\000\006\003\045\015\046\001\002\000\004\013\053\001" +
    "\002\000\004\013\047\001\002\000\006\003\050\014\051" +
    "\001\002\000\004\014\052\001\002\000\004\002\ufff5\001" +
    "\002\000\004\002\ufff2\001\002\000\004\014\054\001\002" +
    "\000\004\002\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\052\000\014\002\005\003\007\004\011\005\010\006" +
    "\006\001\001\000\002\001\001\000\004\007\037\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\004\033\005" +
    "\010\006\032\001\001\000\002\001\001\000\006\005\030" +
    "\006\031\001\001\000\004\007\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\030" +
    "\006\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserAct4$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserAct4$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserAct4$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private boolean fatal = false;

    public boolean huboErrorFatal() {
        return fatal;
    }

    @Override
    public void report_error(String message, Object info) {
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            System.out.println("Error sintáctico en línea " + s.left + ", columna " + s.right + ": se encontró '" + (s.value != null ? s.value : "#" + s.sym) + "'");
        } else {
            System.out.println("Error sintáctico: " + message);
        }
    }

    @Override
    public void report_fatal_error(String message, Object info) {
        fatal = true;
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            System.out.println("Error fatal en línea " + s.left + ", columna " + s.right + ": se encontró '" + (s.value != null ? s.value : "#" + s.sym) + "'");
        } else {
            System.out.println("Error fatal: " + message);
        }
        System.out.println("El análisis no puede continuar debido a una estructura inválida.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserAct4$actions {
  private final ParserAct4 parser;

  /** Constructor */
  CUP$ParserAct4$actions(ParserAct4 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserAct4$do_action_part00000000(
    int                        CUP$ParserAct4$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct4$parser,
    java.util.Stack            CUP$ParserAct4$stack,
    int                        CUP$ParserAct4$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserAct4$result;

      /* select the action based on the action number */
      switch (CUP$ParserAct4$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)).value;
		RESULT = start_val;
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserAct4$parser.done_parsing();
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= declaracion_paquete lista_importaciones declaracion_clase 
            {
              Object RESULT =null;
		 
            System.out.println("Estructura de llaves válida");
            System.out.println("Análisis sintáctico finalizado correctamente"); 
         
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= lista_importaciones declaracion_clase 
            {
              Object RESULT =null;
		 
            System.out.println("Estructura de llaves válida");
            System.out.println("Análisis sintáctico finalizado correctamente"); 
         
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicio ::= declaracion_paquete declaracion_clase 
            {
              Object RESULT =null;
		 
            System.out.println("Estructura de llaves válida");
            System.out.println("Análisis sintáctico finalizado correctamente"); 
         
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inicio ::= declaracion_clase 
            {
              Object RESULT =null;
		 
            System.out.println("Estructura de llaves válida");
            System.out.println("Análisis sintáctico finalizado correctamente"); 
         
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaracion_paquete ::= PACKAGE nombre_cualificado PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Paquete reconocido correctamente"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_paquete",1, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaracion_paquete ::= PACKAGE error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("[Recuperación]: Error sintáctico en paquete recuperado hasta ';'"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_paquete",1, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // lista_importaciones ::= lista_importaciones declaracion_importacion 
            {
              Object RESULT =null;

              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("lista_importaciones",2, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_importaciones ::= declaracion_importacion 
            {
              Object RESULT =null;

              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("lista_importaciones",2, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracion_importacion ::= IMPORT nombre_cualificado PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Importación reconocida correctamente"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_importacion",3, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracion_importacion ::= IMPORT nombre_cualificado PUNTO ASTERISCO PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Importación reconocida correctamente"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_importacion",3, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_importacion ::= IMPORT error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("[Recuperación]: Error sintáctico en importación recuperado hasta ';'"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_importacion",3, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracion_clase ::= PUBLIC CLASS IDENTIFICADOR LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;
		 System.out.println("Clase principal reconocida correctamente"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracion_clase ::= CLASS IDENTIFICADOR LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;
		 System.out.println("Clase principal reconocida correctamente"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declaracion_clase ::= PUBLIC CLASS error LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;
		 System.out.println("[Recuperación]: Falta nombre de la clase, recuperado antes de '{'"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declaracion_clase ::= PUBLIC CLASS IDENTIFICADOR LLAVE_IZQ error LLAVE_DER 
            {
              Object RESULT =null;
		 System.out.println("[Recuperación]: Estructura interna de clase inválida, recuperada en '}'"); 
              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("declaracion_clase",4, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-5)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // nombre_cualificado ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("nombre_cualificado",5, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // nombre_cualificado ::= nombre_cualificado PUNTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserAct4$result = parser.getSymbolFactory().newSymbol("nombre_cualificado",5, ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.elementAt(CUP$ParserAct4$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct4$stack.peek()), RESULT);
            }
          return CUP$ParserAct4$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserAct4$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserAct4$do_action(
    int                        CUP$ParserAct4$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct4$parser,
    java.util.Stack            CUP$ParserAct4$stack,
    int                        CUP$ParserAct4$top)
    throws java.lang.Exception
    {
              return CUP$ParserAct4$do_action_part00000000(
                               CUP$ParserAct4$act_num,
                               CUP$ParserAct4$parser,
                               CUP$ParserAct4$stack,
                               CUP$ParserAct4$top);
    }
}

}
