
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_IZQ = 9;
  public static final int ASTERISCO = 8;
  public static final int PUNTO = 7;
  public static final int LLAVE_DER = 10;
  public static final int PUBLIC = 4;
  public static final int PACKAGE = 2;
  public static final int PUNTO_COMA = 6;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IMPORT = 3;
  public static final int IDENTIFICADOR = 11;
  public static final int CLASS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "PUBLIC",
  "CLASS",
  "PUNTO_COMA",
  "PUNTO",
  "ASTERISCO",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "IDENTIFICADOR"
  };
}

