
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act7;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserAct7 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserAct7() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserAct7(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserAct7(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\074\000\002\002\004\000\002\002\003\000\002\003" +
    "\007\000\002\004\005\000\002\005\004\000\002\005\002" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\006\004\000\002\006\004\000\002\006\004\000\002\006" +
    "\004\000\002\006\004\000\002\007\007\000\002\010\011" +
    "\000\002\011\012\000\002\011\011\000\002\015\004\000" +
    "\002\015\003\000\002\016\006\000\002\017\005\000\002" +
    "\020\003\000\002\012\007\000\002\013\011\000\002\014" +
    "\013\000\002\021\003\000\002\022\005\000\002\022\005" +
    "\000\002\022\004\000\002\022\005\000\002\022\003\000" +
    "\002\022\003\000\002\022\003\000\002\023\005\000\002" +
    "\033\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\003\000\002\033\003\000\002\033\003\000\002\024\005" +
    "\000\002\024\005\000\002\024\003\000\002\025\005\000" +
    "\002\025\005\000\002\025\005\000\002\025\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\005\000\002\027\005\000\002\030\006\000\002\031\006" +
    "\000\002\032\005\000\002\032\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\004\004\005\001\002\000\004\002\000\001" +
    "\002\000\004\046\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\037\011\001\002\000" +
    "\004\040\012\001\002\000\004\041\013\001\002\000\030" +
    "\003\ufffc\005\ufffc\007\ufffc\012\ufffc\013\ufffc\014\ufffc\015" +
    "\ufffc\016\ufffc\017\ufffc\042\ufffc\046\ufffc\001\002\000\004" +
    "\002\uffff\001\002\000\030\003\035\005\033\007\017\012" +
    "\021\013\041\014\042\015\025\016\022\017\034\042\020" +
    "\046\026\001\002\000\034\003\ufffa\005\ufffa\007\ufffa\010" +
    "\ufffa\011\ufffa\012\ufffa\013\ufffa\014\ufffa\015\ufffa\016\ufffa" +
    "\017\ufffa\042\ufffa\046\ufffa\001\002\000\004\037\164\001" +
    "\002\000\040\002\ufffe\003\ufffe\005\ufffe\006\ufffe\007\ufffe" +
    "\010\ufffe\011\ufffe\012\ufffe\013\ufffe\014\ufffe\015\ufffe\016" +
    "\ufffe\017\ufffe\042\ufffe\046\ufffe\001\002\000\004\044\163" +
    "\001\002\000\004\037\160\001\002\000\034\003\ufffb\005" +
    "\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\013\ufffb\014\ufffb" +
    "\015\ufffb\016\ufffb\017\ufffb\042\ufffb\046\ufffb\001\002\000" +
    "\004\044\157\001\002\000\004\037\147\001\002\000\004" +
    "\031\145\001\002\000\034\003\ufff8\005\ufff8\007\ufff8\010" +
    "\ufff8\011\ufff8\012\ufff8\013\ufff8\014\ufff8\015\ufff8\016\ufff8" +
    "\017\ufff8\042\ufff8\046\ufff8\001\002\000\034\003\ufffd\005" +
    "\ufffd\007\ufffd\010\ufffd\011\ufffd\012\ufffd\013\ufffd\014\ufffd" +
    "\015\ufffd\016\ufffd\017\ufffd\042\ufffd\046\ufffd\001\002\000" +
    "\004\044\144\001\002\000\004\044\143\001\002\000\004" +
    "\037\135\001\002\000\004\037\127\001\002\000\004\044" +
    "\126\001\002\000\034\003\ufff9\005\ufff9\007\ufff9\010\ufff9" +
    "\011\ufff9\012\ufff9\013\ufff9\014\ufff9\015\ufff9\016\ufff9\017" +
    "\ufff9\042\ufff9\046\ufff9\001\002\000\034\003\ufff6\005\ufff6" +
    "\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\014\ufff6\015" +
    "\ufff6\016\ufff6\017\ufff6\042\ufff6\046\ufff6\001\002\000\034" +
    "\003\ufff7\005\ufff7\007\ufff7\010\ufff7\011\ufff7\012\ufff7\013" +
    "\ufff7\014\ufff7\015\ufff7\016\ufff7\017\ufff7\042\ufff7\046\ufff7" +
    "\001\002\000\004\037\122\001\002\000\004\041\013\001" +
    "\002\000\004\013\044\001\002\000\004\037\045\001\002" +
    "\000\016\022\061\037\053\046\055\047\046\050\054\051" +
    "\050\001\002\000\044\020\uffcc\021\uffcc\023\uffcc\024\uffcc" +
    "\025\uffcc\026\uffcc\027\uffcc\030\uffcc\032\uffcc\033\uffcc\034" +
    "\uffcc\035\uffcc\036\uffcc\040\uffcc\043\uffcc\044\uffcc\045\uffcc" +
    "\001\002\000\012\020\063\021\064\040\uffe4\044\uffe4\001" +
    "\002\000\012\020\uffde\021\uffde\040\uffde\044\uffde\001\002" +
    "\000\040\020\uffd3\021\uffd3\023\uffd3\024\uffd3\025\uffd3\026" +
    "\uffd3\027\uffd3\030\uffd3\032\uffd3\033\uffd3\034\110\035\107" +
    "\036\106\040\uffd3\044\uffd3\001\002\000\012\020\uffdf\021" +
    "\uffdf\040\uffdf\044\uffdf\001\002\000\016\022\061\037\053" +
    "\046\055\047\046\050\054\051\050\001\002\000\044\020" +
    "\uffcd\021\uffcd\023\uffcd\024\uffcd\025\uffcd\026\uffcd\027\uffcd" +
    "\030\uffcd\032\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd\040" +
    "\uffcd\043\uffcd\044\uffcd\045\uffcd\001\002\000\040\020\uffdd" +
    "\021\uffdd\023\uffce\024\uffce\025\uffce\026\uffce\027\uffce\030" +
    "\uffce\032\uffce\033\uffce\034\uffce\035\uffce\036\uffce\040\uffdd" +
    "\044\uffdd\001\002\000\004\040\115\001\002\000\040\020" +
    "\uffcf\021\uffcf\023\uffcf\024\uffcf\025\uffcf\026\uffcf\027\uffcf" +
    "\030\uffcf\032\uffcf\033\uffcf\034\uffcf\035\uffcf\036\uffcf\040" +
    "\uffcf\044\uffcf\001\002\000\022\023\071\024\076\025\077" +
    "\026\072\027\070\030\074\032\073\033\067\001\002\000" +
    "\016\022\061\037\053\046\055\047\046\050\054\051\050" +
    "\001\002\000\012\020\uffe1\021\uffe1\040\uffe1\044\uffe1\001" +
    "\002\000\016\022\061\037\053\046\055\047\046\050\054" +
    "\051\050\001\002\000\016\022\061\037\053\046\055\047" +
    "\046\050\054\051\050\001\002\000\012\020\063\021\uffe3" +
    "\040\uffe3\044\uffe3\001\002\000\012\020\uffe2\021\uffe2\040" +
    "\uffe2\044\uffe2\001\002\000\012\037\101\046\100\047\046" +
    "\050\054\001\002\000\012\037\uffda\046\uffda\047\uffda\050" +
    "\uffda\001\002\000\012\037\uffd7\046\uffd7\047\uffd7\050\uffd7" +
    "\001\002\000\012\037\uffd9\046\uffd9\047\uffd9\050\uffd9\001" +
    "\002\000\012\037\101\046\100\047\046\050\054\001\002" +
    "\000\012\037\uffdb\046\uffdb\047\uffdb\050\uffdb\001\002\000" +
    "\012\037\101\046\100\047\046\050\054\001\002\000\012" +
    "\037\uffd6\046\uffd6\047\uffd6\050\uffd6\001\002\000\012\037" +
    "\uffd8\046\uffd8\047\uffd8\050\uffd8\001\002\000\044\020\uffce" +
    "\021\uffce\023\uffce\024\uffce\025\uffce\026\uffce\027\uffce\030" +
    "\uffce\032\uffce\033\uffce\034\uffce\035\uffce\036\uffce\040\uffce" +
    "\043\uffce\044\uffce\045\uffce\001\002\000\012\037\101\046" +
    "\100\047\046\050\054\001\002\000\016\020\uffdc\021\uffdc" +
    "\032\073\033\067\040\uffdc\044\uffdc\001\002\000\010\032" +
    "\073\033\067\040\104\001\002\000\044\020\uffcb\021\uffcb" +
    "\023\uffcb\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030\uffcb\032" +
    "\uffcb\033\uffcb\034\uffcb\035\uffcb\036\uffcb\040\uffcb\043\uffcb" +
    "\044\uffcb\045\uffcb\001\002\000\040\020\uffd5\021\uffd5\023" +
    "\uffd5\024\uffd5\025\uffd5\026\uffd5\027\uffd5\030\uffd5\032\uffd5" +
    "\033\uffd5\034\110\035\107\036\106\040\uffd5\044\uffd5\001" +
    "\002\000\012\037\101\046\100\047\046\050\054\001\002" +
    "\000\012\037\101\046\100\047\046\050\054\001\002\000" +
    "\012\037\101\046\100\047\046\050\054\001\002\000\040" +
    "\020\uffd2\021\uffd2\023\uffd2\024\uffd2\025\uffd2\026\uffd2\027" +
    "\uffd2\030\uffd2\032\uffd2\033\uffd2\034\uffd2\035\uffd2\036\uffd2" +
    "\040\uffd2\044\uffd2\001\002\000\040\020\uffd1\021\uffd1\023" +
    "\uffd1\024\uffd1\025\uffd1\026\uffd1\027\uffd1\030\uffd1\032\uffd1" +
    "\033\uffd1\034\uffd1\035\uffd1\036\uffd1\040\uffd1\044\uffd1\001" +
    "\002\000\040\020\uffd0\021\uffd0\023\uffd0\024\uffd0\025\uffd0" +
    "\026\uffd0\027\uffd0\030\uffd0\032\uffd0\033\uffd0\034\uffd0\035" +
    "\uffd0\036\uffd0\040\uffd0\044\uffd0\001\002\000\040\020\uffd4" +
    "\021\uffd4\023\uffd4\024\uffd4\025\uffd4\026\uffd4\027\uffd4\030" +
    "\uffd4\032\uffd4\033\uffd4\034\110\035\107\036\106\040\uffd4" +
    "\044\uffd4\001\002\000\004\044\116\001\002\000\034\003" +
    "\uffe6\005\uffe6\007\uffe6\010\uffe6\011\uffe6\012\uffe6\013\uffe6" +
    "\014\uffe6\015\uffe6\016\uffe6\017\uffe6\042\uffe6\046\uffe6\001" +
    "\002\000\010\020\063\021\064\040\121\001\002\000\024" +
    "\023\071\024\076\025\077\026\072\027\070\030\074\032" +
    "\073\033\067\040\104\001\002\000\012\020\uffe0\021\uffe0" +
    "\040\uffe0\044\uffe0\001\002\000\016\022\061\037\053\046" +
    "\055\047\046\050\054\051\050\001\002\000\004\040\124" +
    "\001\002\000\004\041\013\001\002\000\034\003\uffe7\005" +
    "\uffe7\007\uffe7\010\uffe7\011\uffe7\012\uffe7\013\uffe7\014\uffe7" +
    "\015\uffe7\016\uffe7\017\uffe7\042\uffe7\046\uffe7\001\002\000" +
    "\034\003\ufff1\005\ufff1\007\ufff1\010\ufff1\011\ufff1\012\ufff1" +
    "\013\ufff1\014\ufff1\015\ufff1\016\ufff1\017\ufff1\042\ufff1\046" +
    "\ufff1\001\002\000\012\037\101\046\100\047\046\050\054" +
    "\001\002\000\006\040\uffc6\045\uffc6\001\002\000\006\040" +
    "\133\045\132\001\002\000\012\037\101\046\100\047\046" +
    "\050\054\001\002\000\004\044\uffc8\001\002\000\006\040" +
    "\uffc7\045\uffc7\001\002\000\016\022\061\037\053\046\055" +
    "\047\046\050\054\051\050\001\002\000\004\040\137\001" +
    "\002\000\004\041\013\001\002\000\036\003\ufff0\005\ufff0" +
    "\006\141\007\ufff0\010\ufff0\011\ufff0\012\ufff0\013\ufff0\014" +
    "\ufff0\015\ufff0\016\ufff0\017\ufff0\042\ufff0\046\ufff0\001\002" +
    "\000\004\041\013\001\002\000\034\003\uffef\005\uffef\007" +
    "\uffef\010\uffef\011\uffef\012\uffef\013\uffef\014\uffef\015\uffef" +
    "\016\uffef\017\uffef\042\uffef\046\uffef\001\002\000\034\003" +
    "\ufff4\005\ufff4\007\ufff4\010\ufff4\011\ufff4\012\ufff4\013\ufff4" +
    "\014\ufff4\015\ufff4\016\ufff4\017\ufff4\042\ufff4\046\ufff4\001" +
    "\002\000\034\003\ufff3\005\ufff3\007\ufff3\010\ufff3\011\ufff3" +
    "\012\ufff3\013\ufff3\014\ufff3\015\ufff3\016\ufff3\017\ufff3\042" +
    "\ufff3\046\ufff3\001\002\000\012\037\101\046\100\047\046" +
    "\050\054\001\002\000\012\032\073\033\067\040\uffca\044" +
    "\uffca\001\002\000\004\046\026\001\002\000\004\044\151" +
    "\001\002\000\016\022\061\037\053\046\055\047\046\050" +
    "\054\051\050\001\002\000\004\044\153\001\002\000\004" +
    "\046\026\001\002\000\004\040\155\001\002\000\004\041" +
    "\013\001\002\000\034\003\uffe5\005\uffe5\007\uffe5\010\uffe5" +
    "\011\uffe5\012\uffe5\013\uffe5\014\uffe5\015\uffe5\016\uffe5\017" +
    "\uffe5\042\uffe5\046\uffe5\001\002\000\034\003\ufff5\005\ufff5" +
    "\007\ufff5\010\ufff5\011\ufff5\012\ufff5\013\ufff5\014\ufff5\015" +
    "\ufff5\016\ufff5\017\ufff5\042\ufff5\046\ufff5\001\002\000\004" +
    "\046\161\001\002\000\004\040\162\001\002\000\004\044" +
    "\uffc9\001\002\000\034\003\ufff2\005\ufff2\007\ufff2\010\ufff2" +
    "\011\ufff2\012\ufff2\013\ufff2\014\ufff2\015\ufff2\016\ufff2\017" +
    "\ufff2\042\ufff2\046\ufff2\001\002\000\004\046\165\001\002" +
    "\000\004\040\166\001\002\000\004\041\167\001\002\000" +
    "\004\010\172\001\002\000\010\010\uffeb\011\uffeb\042\uffeb" +
    "\001\002\000\010\010\172\011\201\042\200\001\002\000" +
    "\012\037\101\046\100\047\046\050\054\001\002\000\004" +
    "\043\174\001\002\000\034\003\ufffc\005\ufffc\007\ufffc\010" +
    "\ufffc\011\ufffc\012\ufffc\013\ufffc\014\ufffc\015\ufffc\016\ufffc" +
    "\017\ufffc\042\ufffc\046\ufffc\001\002\000\034\003\035\005" +
    "\033\007\017\010\uffe8\011\uffe8\012\021\013\041\014\042" +
    "\015\025\016\022\017\034\042\uffe8\046\026\001\002\000" +
    "\010\010\uffea\011\uffea\042\uffea\001\002\000\010\010\uffec" +
    "\011\uffec\042\uffec\001\002\000\034\003\uffed\005\uffed\007" +
    "\uffed\010\uffed\011\uffed\012\uffed\013\uffed\014\uffed\015\uffed" +
    "\016\uffed\017\uffed\042\uffed\046\uffed\001\002\000\004\043" +
    "\204\001\002\000\004\042\203\001\002\000\034\003\uffee" +
    "\005\uffee\007\uffee\010\uffee\011\uffee\012\uffee\013\uffee\014" +
    "\uffee\015\uffee\016\uffee\017\uffee\042\uffee\046\uffee\001\002" +
    "\000\030\003\ufffc\005\ufffc\007\ufffc\012\ufffc\013\ufffc\014" +
    "\ufffc\015\ufffc\016\ufffc\017\ufffc\042\ufffc\046\ufffc\001\002" +
    "\000\004\042\uffe9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\203\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\013\001" +
    "\001\000\004\005\014\001\001\000\002\001\001\000\026" +
    "\006\027\007\022\010\015\011\035\012\026\013\037\014" +
    "\036\027\023\030\031\031\030\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\042\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\021\055\022\046\023\051\024\057\025\050\026\056" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\022\116" +
    "\023\051\024\117\025\050\026\056\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\033\074\001\001\000\014\022\061\023\051\024" +
    "\057\025\050\026\056\001\001\000\002\001\001\000\014" +
    "\022\065\023\051\024\057\025\050\026\056\001\001\000" +
    "\014\022\064\023\051\024\057\025\050\026\056\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\025\113\026" +
    "\056\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\025\104\026\056\001\001\000\002\001" +
    "\001\000\010\024\101\025\050\026\056\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\024" +
    "\102\025\050\026\056\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\026" +
    "\112\001\001\000\004\026\111\001\001\000\004\026\110" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\033\074\001\001\000\002\001" +
    "\001\000\016\021\122\022\046\023\051\024\057\025\050" +
    "\026\056\001\001\000\002\001\001\000\004\004\124\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\026\127" +
    "\032\130\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\026\133\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\021\135\022\046\023\051\024\057\025\050\026" +
    "\056\001\001\000\002\001\001\000\004\004\137\001\001" +
    "\000\002\001\001\000\004\004\141\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\024\145" +
    "\025\050\026\056\001\001\000\002\001\001\000\004\027" +
    "\147\001\001\000\002\001\001\000\016\021\151\022\046" +
    "\023\051\024\057\025\050\026\056\001\001\000\002\001" +
    "\001\000\004\027\153\001\001\000\002\001\001\000\004" +
    "\004\155\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\015\170\016\167\001\001\000\002\001\001" +
    "\000\006\016\176\017\201\001\001\000\004\026\172\001" +
    "\001\000\002\001\001\000\006\005\174\020\175\001\001" +
    "\000\026\006\027\007\022\010\015\011\035\012\026\013" +
    "\037\014\036\027\023\030\031\031\030\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\174" +
    "\020\204\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserAct7$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserAct7$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserAct7$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol cur_token) {
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : "desconocido";
        System.err.println("Error sintáctico en línea " + cur_token.left + ", columna " + cur_token.right 
            + ": Token inesperado '" + lexema + "'");
    }

    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        System.err.println("Error sintáctico no recuperable en línea " + cur_token.left + ", columna " + cur_token.right + ".");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserAct7$actions {
  private final ParserAct7 parser;

  /** Constructor */
  CUP$ParserAct7$actions(ParserAct7 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserAct7$do_action_part00000000(
    int                        CUP$ParserAct7$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct7$parser,
    java.util.Stack            CUP$ParserAct7$stack,
    int                        CUP$ParserAct7$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserAct7$result;

      /* select the action based on the action number */
      switch (CUP$ParserAct7$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)).value;
		RESULT = start_val;
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserAct7$parser.done_parsing();
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= metodo 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: inicio"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // metodo ::= VOID ID PAR_ABRE PAR_CIERRA bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: metodo"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("metodo",1, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloque ::= LLAVE_ABRE lista_sentencias LLAVE_CIERRA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: bloque"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lista_sentencias",3, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_sentencias ::= 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lista_sentencias",3, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= seleccion_simple 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= seleccion_doble 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= seleccion_multiple 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= ciclo_mientras 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= ciclo_hacer_mientras 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= ciclo_para 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= asignacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= lectura PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= escritura PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= ROMPER PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: sentencia_romper"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Recuperación de error en sentencia finalizada en ';'"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("sentencia",4, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // seleccion_simple ::= SI PAR_ABRE condicion PAR_CIERRA bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: seleccion_simple"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("seleccion_simple",5, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // seleccion_doble ::= SI PAR_ABRE condicion PAR_CIERRA bloque SINO bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: seleccion_doble"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("seleccion_doble",6, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-6)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // seleccion_multiple ::= SEGUN PAR_ABRE ID PAR_CIERRA LLAVE_ABRE lista_casos caso_defecto LLAVE_CIERRA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: seleccion_multiple"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("seleccion_multiple",7, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-7)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // seleccion_multiple ::= SEGUN PAR_ABRE ID PAR_CIERRA LLAVE_ABRE lista_casos LLAVE_CIERRA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: seleccion_multiple"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("seleccion_multiple",7, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-6)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_casos ::= lista_casos caso_elemento 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lista_casos",11, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_casos ::= caso_elemento 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lista_casos",11, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // caso_elemento ::= CASO factor DOS_PUNTOS cuerpo_caso 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: caso"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("caso_elemento",12, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // caso_defecto ::= DEFECTO DOS_PUNTOS cuerpo_caso 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: defecto"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("caso_defecto",13, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // cuerpo_caso ::= lista_sentencias 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("cuerpo_caso",14, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ciclo_mientras ::= MIENTRAS PAR_ABRE condicion PAR_CIERRA bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: ciclo_mientras"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("ciclo_mientras",8, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-4)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ciclo_hacer_mientras ::= HACER bloque MIENTRAS PAR_ABRE condicion PAR_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: ciclo_hacer_mientras"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("ciclo_hacer_mientras",9, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-6)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ciclo_para ::= PARA PAR_ABRE asignacion PUNTO_COMA condicion PUNTO_COMA asignacion PAR_CIERRA bloque 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: ciclo_para"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("ciclo_para",10, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-8)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condicion ::= expresion_logica 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: condicion"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("condicion",15, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion_logica ::= expresion_logica OR expresion_logica 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: condicion_compuesta (OR)"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion_logica ::= expresion_logica AND expresion_logica 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: condicion_compuesta (AND)"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion_logica ::= NOT expresion_logica 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: condicion_negacion"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-1)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion_logica ::= PAR_ABRE expresion_logica PAR_CIERRA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: condicion_agrupada"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion_logica ::= expresion_relacional 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion_logica ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion_logica ::= ID 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_logica",16, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion_relacional ::= expresion_aritmetica op_relacional expresion_aritmetica 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: condicion_simple (relacional)"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_relacional",17, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // op_relacional ::= MAYOR 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("op_relacional",25, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // op_relacional ::= MENOR 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("op_relacional",25, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // op_relacional ::= MAYOR_IGUAL 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("op_relacional",25, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // op_relacional ::= MENOR_IGUAL 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("op_relacional",25, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // op_relacional ::= IGUAL_IGUAL 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("op_relacional",25, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // op_relacional ::= DIFERENTE 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("op_relacional",25, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion_aritmetica ::= expresion_aritmetica MAS termino 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_aritmetica",18, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion_aritmetica ::= expresion_aritmetica MENOS termino 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_aritmetica",18, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion_aritmetica ::= termino 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("expresion_aritmetica",18, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // termino ::= termino POR factor 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // termino ::= termino DIV factor 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // termino ::= termino MOD factor 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // termino ::= factor 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // factor ::= ID 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // factor ::= NUMERO 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // factor ::= CADENA 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // factor ::= PAR_ABRE expresion_aritmetica PAR_CIERRA 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // asignacion ::= ID ASIGNACION expresion_aritmetica 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: asignacion"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("asignacion",21, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // lectura ::= LEER PAR_ABRE ID PAR_CIERRA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: lectura"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lectura",22, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // escritura ::= ESCRIBIR PAR_ABRE lista_argumentos PAR_CIERRA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: escritura"); 
              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("escritura",23, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-3)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // lista_argumentos ::= lista_argumentos COMA factor 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lista_argumentos",24, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.elementAt(CUP$ParserAct7$top-2)), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // lista_argumentos ::= factor 
            {
              Object RESULT =null;

              CUP$ParserAct7$result = parser.getSymbolFactory().newSymbol("lista_argumentos",24, ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserAct7$stack.peek()), RESULT);
            }
          return CUP$ParserAct7$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserAct7$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserAct7$do_action(
    int                        CUP$ParserAct7$act_num,
    java_cup.runtime.lr_parser CUP$ParserAct7$parser,
    java.util.Stack            CUP$ParserAct7$stack,
    int                        CUP$ParserAct7$top)
    throws java.lang.Exception
    {
              return CUP$ParserAct7$do_action_part00000000(
                               CUP$ParserAct7$act_num,
                               CUP$ParserAct7$parser,
                               CUP$ParserAct7$stack,
                               CUP$ParserAct7$top);
    }
}

}
