
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act7;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 38;
  public static final int CASO = 6;
  public static final int POR = 26;
  public static final int SI = 3;
  public static final int DIFERENTE = 18;
  public static final int DOS_PUNTOS = 33;
  public static final int PAR_ABRE = 29;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int SINO = 4;
  public static final int OR = 15;
  public static final int MIENTRAS = 9;
  public static final int ESCRIBIR = 13;
  public static final int DIV = 27;
  public static final int ID = 36;
  public static final int PUNTO_COMA = 34;
  public static final int IGUAL_IGUAL = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 35;
  public static final int CADENA = 37;
  public static final int MENOS = 25;
  public static final int MENOR = 21;
  public static final int MOD = 28;
  public static final int VOID = 2;
  public static final int LLAVE_ABRE = 31;
  public static final int ASIGNACION = 23;
  public static final int MAYOR = 22;
  public static final int ROMPER = 8;
  public static final int MAYOR_IGUAL = 20;
  public static final int LEER = 12;
  public static final int SEGUN = 5;
  public static final int HACER = 10;
  public static final int BOOLEANO = 39;
  public static final int PARA = 11;
  public static final int LLAVE_CIERRA = 32;
  public static final int MENOR_IGUAL = 19;
  public static final int PAR_CIERRA = 30;
  public static final int DEFECTO = 7;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "SI",
  "SINO",
  "SEGUN",
  "CASO",
  "DEFECTO",
  "ROMPER",
  "MIENTRAS",
  "HACER",
  "PARA",
  "LEER",
  "ESCRIBIR",
  "AND",
  "OR",
  "NOT",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "MENOR",
  "MAYOR",
  "ASIGNACION",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "PAR_ABRE",
  "PAR_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "COMA",
  "ID",
  "CADENA",
  "NUMERO",
  "BOOLEANO"
  };
}

