
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act8;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserJava extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserJava() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserJava(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserJava(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\005\010\000\002\005\006\000\002\006\003\000" +
    "\002\006\002\000\002\007\005\000\002\007\003\000\002" +
    "\007\005\000\002\007\005\000\002\010\005\000\002\010" +
    "\004\000\002\011\004\000\002\011\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\013\007\000" +
    "\002\013\005\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\012\006\000\002\012\007\000\002\012" +
    "\007\000\002\012\011\000\002\012\007\000\002\012\014" +
    "\000\002\012\004\000\002\012\004\000\002\015\005\000" +
    "\002\015\004\000\002\015\005\000\002\017\004\000\002" +
    "\016\006\000\002\016\006\000\002\020\003\000\002\020" +
    "\002\000\002\021\005\000\002\021\003\000\002\021\005" +
    "\000\002\021\004\000\002\022\003\000\002\023\005\000" +
    "\002\023\005\000\002\023\005\000\002\023\005\000\002" +
    "\023\003\000\002\024\005\000\002\024\005\000\002\024" +
    "\003\000\002\025\005\000\002\025\005\000\002\025\005" +
    "\000\002\025\003\000\002\026\003\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\026\003\000\002\026\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\030\003\022\004\012\005\011\006\023\007" +
    "\027\010\021\011\013\013\007\014\026\015\010\036\014" +
    "\001\002\000\032\002\ufffd\003\ufffd\004\ufffd\005\ufffd\006" +
    "\ufffd\007\ufffd\010\ufffd\011\ufffd\013\ufffd\014\ufffd\015\ufffd" +
    "\036\ufffd\001\002\000\034\002\uffea\003\uffea\004\uffea\005" +
    "\uffea\006\uffea\007\uffea\010\uffea\011\uffea\013\uffea\014\uffea" +
    "\015\uffea\021\uffea\036\uffea\001\002\000\004\023\201\001" +
    "\002\000\004\016\175\001\002\000\004\016\171\001\002" +
    "\000\022\003\166\016\041\023\164\036\045\037\034\040" +
    "\047\041\043\042\035\001\002\000\004\036\145\001\002" +
    "\000\004\016\137\001\002\000\006\016\050\024\134\001" +
    "\002\000\004\002\133\001\002\000\032\002\ufffe\003\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\013" +
    "\ufffe\014\ufffe\015\ufffe\036\ufffe\001\002\000\032\002\ufffc" +
    "\003\ufffc\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011" +
    "\ufffc\013\ufffc\014\ufffc\015\ufffc\036\ufffc\001\002\000\034" +
    "\002\uffe9\003\uffe9\004\uffe9\005\uffe9\006\uffe9\007\uffe9\010" +
    "\uffe9\011\uffe9\013\uffe9\014\uffe9\015\uffe9\021\uffe9\036\uffe9" +
    "\001\002\000\004\036\uffed\001\002\000\006\021\132\023" +
    "\131\001\002\000\004\036\uffef\001\002\000\004\036\124" +
    "\001\002\000\034\002\uffe8\003\uffe8\004\uffe8\005\uffe8\006" +
    "\uffe8\007\uffe8\010\uffe8\011\uffe8\013\uffe8\014\uffe8\015\uffe8" +
    "\021\uffe8\036\uffe8\001\002\000\004\016\032\001\002\000" +
    "\004\036\uffee\001\002\000\032\002\000\003\022\004\012" +
    "\005\011\006\023\007\027\010\021\011\013\013\007\014" +
    "\026\015\010\036\014\001\002\000\032\002\uffff\003\uffff" +
    "\004\uffff\005\uffff\006\uffff\007\uffff\010\uffff\011\uffff\013" +
    "\uffff\014\uffff\015\uffff\036\uffff\001\002\000\010\006\023" +
    "\007\027\010\021\001\002\000\016\016\041\036\045\037" +
    "\034\040\047\041\043\042\035\001\002\000\032\017\uffc3" +
    "\022\uffc3\023\uffc3\025\uffc3\026\uffc3\027\uffc3\030\uffc3\031" +
    "\uffc3\032\uffc3\033\uffc3\034\uffc3\035\uffc3\001\002\000\032" +
    "\017\uffc2\022\uffc2\023\uffc2\025\uffc2\026\uffc2\027\uffc2\030" +
    "\uffc2\031\uffc2\032\uffc2\033\uffc2\034\uffc2\035\uffc2\001\002" +
    "\000\032\017\uffc1\022\uffc1\023\uffc1\025\uffc1\026\uffc1\027" +
    "\uffc1\030\uffc1\031\uffc1\032\uffc1\033\uffc1\034\uffc1\035\uffc1" +
    "\001\002\000\010\017\uffd3\022\uffd3\023\uffd3\001\002\000" +
    "\024\017\uffce\022\uffce\023\uffce\025\112\026\110\032\111" +
    "\033\113\034\115\035\114\001\002\000\016\016\041\036" +
    "\045\037\034\040\047\041\043\042\035\001\002\000\032" +
    "\017\uffcb\022\uffcb\023\uffcb\025\uffcb\026\uffcb\027\101\030" +
    "\102\031\100\032\uffcb\033\uffcb\034\uffcb\035\uffcb\001\002" +
    "\000\032\017\uffc4\022\uffc4\023\uffc4\025\uffc4\026\uffc4\027" +
    "\uffc4\030\uffc4\031\uffc4\032\uffc4\033\uffc4\034\uffc4\035\uffc4" +
    "\001\002\000\004\023\064\001\002\000\034\016\050\017" +
    "\uffc6\022\uffc6\023\uffc6\025\uffc6\026\uffc6\027\uffc6\030\uffc6" +
    "\031\uffc6\032\uffc6\033\uffc6\034\uffc6\035\uffc6\001\002\000" +
    "\032\017\uffc7\022\uffc7\023\uffc7\025\uffc7\026\uffc7\027\uffc7" +
    "\030\uffc7\031\uffc7\032\uffc7\033\uffc7\034\uffc7\035\uffc7\001" +
    "\002\000\032\017\uffc5\022\uffc5\023\uffc5\025\uffc5\026\uffc5" +
    "\027\uffc5\030\uffc5\031\uffc5\032\uffc5\033\uffc5\034\uffc5\035" +
    "\uffc5\001\002\000\024\003\054\016\041\017\uffd8\022\051" +
    "\036\045\037\034\040\047\041\043\042\035\001\002\000" +
    "\016\016\041\036\045\037\034\040\047\041\043\042\035" +
    "\001\002\000\004\017\062\001\002\000\006\017\uffd6\022" +
    "\uffd6\001\002\000\004\017\061\001\002\000\006\017\uffd9" +
    "\022\056\001\002\000\020\003\060\016\041\036\045\037" +
    "\034\040\047\041\043\042\035\001\002\000\006\017\uffd7" +
    "\022\uffd7\001\002\000\006\017\uffd5\022\uffd5\001\002\000" +
    "\032\017\uffda\022\uffda\023\uffda\025\uffda\026\uffda\027\uffda" +
    "\030\uffda\031\uffda\032\uffda\033\uffda\034\uffda\035\uffda\001" +
    "\002\000\032\017\uffdb\022\uffdb\023\uffdb\025\uffdb\026\uffdb" +
    "\027\uffdb\030\uffdb\031\uffdb\032\uffdb\033\uffdb\034\uffdb\035" +
    "\uffdb\001\002\000\006\017\uffd4\022\uffd4\001\002\000\004" +
    "\036\065\001\002\000\004\024\066\001\002\000\016\016" +
    "\041\036\045\037\034\040\047\041\043\042\035\001\002" +
    "\000\004\017\070\001\002\000\004\020\071\001\002\000" +
    "\030\003\022\005\011\006\023\007\027\010\021\011\013" +
    "\013\007\014\026\015\010\021\075\036\014\001\002\000" +
    "\034\002\uffe2\003\uffe2\004\uffe2\005\uffe2\006\uffe2\007\uffe2" +
    "\010\uffe2\011\uffe2\013\uffe2\014\uffe2\015\uffe2\021\uffe2\036" +
    "\uffe2\001\002\000\030\003\022\005\011\006\023\007\027" +
    "\010\021\011\013\013\007\014\026\015\010\021\076\036" +
    "\014\001\002\000\030\003\ufff0\005\ufff0\006\ufff0\007\ufff0" +
    "\010\ufff0\011\ufff0\013\ufff0\014\ufff0\015\ufff0\021\ufff0\036" +
    "\ufff0\001\002\000\036\002\ufff2\003\ufff2\004\ufff2\005\ufff2" +
    "\006\ufff2\007\ufff2\010\ufff2\011\ufff2\012\ufff2\013\ufff2\014" +
    "\ufff2\015\ufff2\021\ufff2\036\ufff2\001\002\000\036\002\ufff3" +
    "\003\ufff3\004\ufff3\005\ufff3\006\ufff3\007\ufff3\010\ufff3\011" +
    "\ufff3\012\ufff3\013\ufff3\014\ufff3\015\ufff3\021\ufff3\036\ufff3" +
    "\001\002\000\030\003\ufff1\005\ufff1\006\ufff1\007\ufff1\010" +
    "\ufff1\011\ufff1\013\ufff1\014\ufff1\015\ufff1\021\ufff1\036\ufff1" +
    "\001\002\000\016\016\041\036\045\037\034\040\047\041" +
    "\043\042\035\001\002\000\016\016\041\036\045\037\034" +
    "\040\047\041\043\042\035\001\002\000\016\016\041\036" +
    "\045\037\034\040\047\041\043\042\035\001\002\000\032" +
    "\017\uffc9\022\uffc9\023\uffc9\025\uffc9\026\uffc9\027\uffc9\030" +
    "\uffc9\031\uffc9\032\uffc9\033\uffc9\034\uffc9\035\uffc9\001\002" +
    "\000\032\017\uffca\022\uffca\023\uffca\025\uffca\026\uffca\027" +
    "\uffca\030\uffca\031\uffca\032\uffca\033\uffca\034\uffca\035\uffca" +
    "\001\002\000\032\017\uffc8\022\uffc8\023\uffc8\025\uffc8\026" +
    "\uffc8\027\uffc8\030\uffc8\031\uffc8\032\uffc8\033\uffc8\034\uffc8" +
    "\035\uffc8\001\002\000\004\017\107\001\002\000\032\017" +
    "\uffc0\022\uffc0\023\uffc0\025\uffc0\026\uffc0\027\uffc0\030\uffc0" +
    "\031\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0\001\002\000" +
    "\016\016\041\036\045\037\034\040\047\041\043\042\035" +
    "\001\002\000\016\016\041\036\045\037\034\040\047\041" +
    "\043\042\035\001\002\000\016\016\041\036\045\037\034" +
    "\040\047\041\043\042\035\001\002\000\016\016\041\036" +
    "\045\037\034\040\047\041\043\042\035\001\002\000\016" +
    "\016\041\036\045\037\034\040\047\041\043\042\035\001" +
    "\002\000\016\016\041\036\045\037\034\040\047\041\043" +
    "\042\035\001\002\000\014\017\uffd0\022\uffd0\023\uffd0\025" +
    "\112\026\110\001\002\000\014\017\uffcf\022\uffcf\023\uffcf" +
    "\025\112\026\110\001\002\000\014\017\uffd1\022\uffd1\023" +
    "\uffd1\025\112\026\110\001\002\000\032\017\uffcd\022\uffcd" +
    "\023\uffcd\025\uffcd\026\uffcd\027\101\030\102\031\100\032" +
    "\uffcd\033\uffcd\034\uffcd\035\uffcd\001\002\000\014\017\uffd2" +
    "\022\uffd2\023\uffd2\025\112\026\110\001\002\000\032\017" +
    "\uffcc\022\uffcc\023\uffcc\025\uffcc\026\uffcc\027\101\030\102" +
    "\031\100\032\uffcc\033\uffcc\034\uffcc\035\uffcc\001\002\000" +
    "\006\023\125\024\126\001\002\000\046\002\uffeb\003\uffeb" +
    "\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\011\uffeb\013" +
    "\uffeb\014\uffeb\015\uffeb\016\uffeb\021\uffeb\036\uffeb\037\uffeb" +
    "\040\uffeb\041\uffeb\042\uffeb\001\002\000\016\016\041\036" +
    "\045\037\034\040\047\041\043\042\035\001\002\000\004" +
    "\023\130\001\002\000\046\002\uffec\003\uffec\004\uffec\005" +
    "\uffec\006\uffec\007\uffec\010\uffec\011\uffec\013\uffec\014\uffec" +
    "\015\uffec\016\uffec\021\uffec\036\uffec\037\uffec\040\uffec\041" +
    "\uffec\042\uffec\001\002\000\034\002\uffe1\003\uffe1\004\uffe1" +
    "\005\uffe1\006\uffe1\007\uffe1\010\uffe1\011\uffe1\013\uffe1\014" +
    "\uffe1\015\uffe1\021\uffe1\036\uffe1\001\002\000\034\002\uffe0" +
    "\003\uffe0\004\uffe0\005\uffe0\006\uffe0\007\uffe0\010\uffe0\011" +
    "\uffe0\013\uffe0\014\uffe0\015\uffe0\021\uffe0\036\uffe0\001\002" +
    "\000\004\002\001\001\002\000\016\016\041\036\045\037" +
    "\034\040\047\041\043\042\035\001\002\000\004\023\136" +
    "\001\002\000\034\002\uffe7\003\uffe7\004\uffe7\005\uffe7\006" +
    "\uffe7\007\uffe7\010\uffe7\011\uffe7\013\uffe7\014\uffe7\015\uffe7" +
    "\021\uffe7\036\uffe7\001\002\000\016\016\041\036\045\037" +
    "\034\040\047\041\043\042\035\001\002\000\004\017\141" +
    "\001\002\000\004\020\071\001\002\000\036\002\uffe5\003" +
    "\uffe5\004\uffe5\005\uffe5\006\uffe5\007\uffe5\010\uffe5\011\uffe5" +
    "\012\143\013\uffe5\014\uffe5\015\uffe5\021\uffe5\036\uffe5\001" +
    "\002\000\004\020\071\001\002\000\034\002\uffe4\003\uffe4" +
    "\004\uffe4\005\uffe4\006\uffe4\007\uffe4\010\uffe4\011\uffe4\013" +
    "\uffe4\014\uffe4\015\uffe4\021\uffe4\036\uffe4\001\002\000\006" +
    "\003\146\016\147\001\002\000\004\020\071\001\002\000" +
    "\010\003\151\017\ufff8\036\150\001\002\000\006\017\ufff6" +
    "\022\ufff6\001\002\000\004\022\161\001\002\000\004\017" +
    "\157\001\002\000\006\017\ufff9\022\154\001\002\000\006" +
    "\003\156\036\155\001\002\000\006\017\ufff7\022\ufff7\001" +
    "\002\000\006\017\ufff5\022\ufff5\001\002\000\004\020\071" +
    "\001\002\000\032\002\ufffb\003\ufffb\004\ufffb\005\ufffb\006" +
    "\ufffb\007\ufffb\010\ufffb\011\ufffb\013\ufffb\014\ufffb\015\ufffb" +
    "\036\ufffb\001\002\000\004\036\162\001\002\000\006\017" +
    "\ufff4\022\ufff4\001\002\000\032\002\ufffa\003\ufffa\004\ufffa" +
    "\005\ufffa\006\ufffa\007\ufffa\010\ufffa\011\ufffa\013\ufffa\014" +
    "\ufffa\015\ufffa\036\ufffa\001\002\000\034\002\uffde\003\uffde" +
    "\004\uffde\005\uffde\006\uffde\007\uffde\010\uffde\011\uffde\013" +
    "\uffde\014\uffde\015\uffde\021\uffde\036\uffde\001\002\000\004" +
    "\023\170\001\002\000\004\023\167\001\002\000\034\002" +
    "\uffdd\003\uffdd\004\uffdd\005\uffdd\006\uffdd\007\uffdd\010\uffdd" +
    "\011\uffdd\013\uffdd\014\uffdd\015\uffdd\021\uffdd\036\uffdd\001" +
    "\002\000\034\002\uffdf\003\uffdf\004\uffdf\005\uffdf\006\uffdf" +
    "\007\uffdf\010\uffdf\011\uffdf\013\uffdf\014\uffdf\015\uffdf\021" +
    "\uffdf\036\uffdf\001\002\000\016\016\041\036\045\037\034" +
    "\040\047\041\043\042\035\001\002\000\004\017\173\001" +
    "\002\000\004\023\174\001\002\000\034\002\uffe6\003\uffe6" +
    "\004\uffe6\005\uffe6\006\uffe6\007\uffe6\010\uffe6\011\uffe6\013" +
    "\uffe6\014\uffe6\015\uffe6\021\uffe6\036\uffe6\001\002\000\016" +
    "\016\041\036\045\037\034\040\047\041\043\042\035\001" +
    "\002\000\004\017\177\001\002\000\004\020\071\001\002" +
    "\000\034\002\uffe3\003\uffe3\004\uffe3\005\uffe3\006\uffe3\007" +
    "\uffe3\010\uffe3\011\uffe3\013\uffe3\014\uffe3\015\uffe3\021\uffe3" +
    "\036\uffe3\001\002\000\034\002\uffdc\003\uffdc\004\uffdc\005" +
    "\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc\013\uffdc\014\uffdc" +
    "\015\uffdc\021\uffdc\036\uffdc\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\026\002\014\003\027\004\015\005\003\012" +
    "\016\013\024\014\023\015\017\016\005\017\004\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\016\035\022\164" +
    "\023\036\024\037\025\041\026\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\004\030\005\003\012\016\013\024\014\023" +
    "\015\017\016\005\017\004\001\001\000\002\001\001\000" +
    "\006\013\032\014\023\001\001\000\016\016\035\022\043" +
    "\023\036\024\037\025\041\026\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\016\035\022\105\023\036\024" +
    "\037\025\041\026\045\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\016\035\020\051\021\054" +
    "\022\052\023\036\024\037\025\041\026\045\001\001\000" +
    "\016\016\035\022\062\023\036\024\037\025\041\026\045" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\016\035\022\056\023\036" +
    "\024\037\025\041\026\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\016" +
    "\035\022\066\023\036\024\037\025\041\026\045\001\001" +
    "\000\002\001\001\000\004\010\071\001\001\000\020\011" +
    "\072\012\073\013\024\014\023\015\017\016\005\017\004" +
    "\001\001\000\002\001\001\000\016\012\076\013\024\014" +
    "\023\015\017\016\005\017\004\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\016\035\026\104\001\001\000\006\016\035\026\103" +
    "\001\001\000\006\016\035\026\102\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\016\035\025\122\026\045\001" +
    "\001\000\012\016\035\024\121\025\041\026\045\001\001" +
    "\000\010\016\035\025\120\026\045\001\001\000\012\016" +
    "\035\024\117\025\041\026\045\001\001\000\012\016\035" +
    "\024\116\025\041\026\045\001\001\000\012\016\035\024" +
    "\115\025\041\026\045\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\016\035\022\126\023\036\024\037\025\041\026" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\016" +
    "\035\022\134\023\036\024\037\025\041\026\045\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\016\035\022" +
    "\137\023\036\024\037\025\041\026\045\001\001\000\002" +
    "\001\001\000\004\010\141\001\001\000\002\001\001\000" +
    "\004\010\143\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\162\001\001\000\006\006\151\007\152\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\157\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\016\035\022\171\023" +
    "\036\024\037\025\041\026\045\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\016\035\022" +
    "\175\023\036\024\037\025\041\026\045\001\001\000\002" +
    "\001\001\000\004\010\177\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserJava$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserJava$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserJava$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol cur_token) {
        System.err.println("Error sintáctico en línea " + cur_token.left + 
                           ", columna " + cur_token.right + 
                           ". Token no esperado: '" + cur_token.value + "'");
    }

    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        System.err.println("Error sintáctico no recuperable en línea " + cur_token.left + 
                           ", columna " + cur_token.right + ".");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserJava$actions {
  private final ParserJava parser;

  /** Constructor */
  CUP$ParserJava$actions(ParserJava parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserJava$do_action_part00000000(
    int                        CUP$ParserJava$act_num,
    java_cup.runtime.lr_parser CUP$ParserJava$parser,
    java.util.Stack            CUP$ParserJava$stack,
    int                        CUP$ParserJava$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserJava$result;

      /* select the action based on the action number */
      switch (CUP$ParserJava$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)).value;
		RESULT = start_val;
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserJava$parser.done_parsing();
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_declaraciones 
            {
              Object RESULT =null;
		 System.out.println("Fin del análisis sintáctico."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_declaraciones ::= lista_declaraciones declaracion 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",1, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_declaraciones ::= declaracion 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_declaraciones",1, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaracion ::= metodo 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaracion ::= sentencia 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declaracion",2, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // metodo ::= FUNCTION ID PARENTESIS_IZQ parametros_optativos PARENTESIS_DER bloque 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)).value;
		
        System.out.println("Regla reconocida: definicion_metodo [" + id + "]");
    
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("metodo",3, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-5)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // metodo ::= FUNCTION ID error bloque 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: faltan paréntesis o firma inválida en función."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("metodo",3, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // parametros_optativos ::= lista_parametros 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: metodo_con_parametros"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("parametros_optativos",4, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // parametros_optativos ::= 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: metodo_sin_parametros"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("parametros_optativos",4, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_parametros ::= lista_parametros COMA ID 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_parametros",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_parametros ::= ID 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_parametros",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_parametros ::= lista_parametros COMA error 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: se esperaba un identificador de parámetro después de ','."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_parametros",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_parametros ::= error COMA ID 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: identificador de parámetro mal estructurado antes de la coma."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_parametros",5, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // bloque ::= LLAVE_IZQ lista_sentencias LLAVE_DER 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("bloque",6, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // bloque ::= LLAVE_IZQ LLAVE_DER 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("bloque",6, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_sentencias",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_sentencias",7, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declarador ::= LET 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declarador",10, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declarador ::= VAR 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declarador",10, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declarador ::= CONST 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declarador",10, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracion_variable ::= declarador ID ASIGNAR expresion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declaracion_variable",9, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracion_variable ::= declarador ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("declaracion_variable",9, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentencia ::= llamada_sentencia 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // sentencia ::= sentencia_retorno 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sentencia ::= declaracion_variable 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sentencia ::= ID ASIGNAR expresion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia ::= CONSOLE_LOG PARENTESIS_IZQ expresion PARENTESIS_DER PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= IF PARENTESIS_IZQ expresion PARENTESIS_DER bloque 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= IF PARENTESIS_IZQ expresion PARENTESIS_DER bloque ELSE bloque 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-6)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia ::= WHILE PARENTESIS_IZQ expresion PARENTESIS_DER bloque 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-4)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia ::= FOR PARENTESIS_IZQ declaracion_variable expresion PUNTO_COMA ID ASIGNAR expresion PARENTESIS_DER bloque 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-9)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.err.println("Punto de recuperación: error sintáctico hasta ';'."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia ::= error LLAVE_DER 
            {
              Object RESULT =null;
		 System.err.println("Punto de recuperación: error sintáctico hasta '}'."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia",8, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sentencia_retorno ::= RETURN expresion PUNTO_COMA 
            {
              Object RESULT =null;
		 
        System.out.println("Regla reconocida: retorno");
        System.out.println("Regla reconocida: metodo_con_retorno");
    
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia_retorno",11, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // sentencia_retorno ::= RETURN PUNTO_COMA 
            {
              Object RESULT =null;
		 
        System.out.println("Regla reconocida: retorno (sin expresion)"); 
        System.out.println("Regla reconocida: metodo_sin_retorno");
    
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia_retorno",11, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sentencia_retorno ::= RETURN error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: se esperaba una expresión válida después de 'return'."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("sentencia_retorno",11, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // llamada_sentencia ::= llamada_metodo PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: llamada como sentencia"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("llamada_sentencia",13, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // llamada_metodo ::= ID PARENTESIS_IZQ argumentos_optativos PARENTESIS_DER 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)).value;
		 System.out.println("Regla reconocida: llamada_metodo [" + id + "]"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("llamada_metodo",12, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // llamada_metodo ::= ID PARENTESIS_IZQ error PARENTESIS_DER 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: argumentos con estructura inválida en llamada."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("llamada_metodo",12, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-3)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // argumentos_optativos ::= lista_argumentos 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("argumentos_optativos",14, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // argumentos_optativos ::= 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("argumentos_optativos",14, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_argumentos ::= lista_argumentos COMA expresion 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: lista_argumentos"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_argumentos",15, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lista_argumentos ::= expresion 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: lista_argumentos"); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_argumentos",15, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // lista_argumentos ::= lista_argumentos COMA error 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: se esperaba una expresión después de ','."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_argumentos",15, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_argumentos ::= COMA expresion 
            {
              Object RESULT =null;
		 System.err.println("Error sintáctico: falta argumento previo a la coma."); 
              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("lista_argumentos",15, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-1)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= expresion_rel 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion",16, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion_rel ::= expresion_arit IGUAL expresion_arit 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_rel",17, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion_rel ::= expresion_arit IGUAL_ESTRICTO expresion_arit 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_rel",17, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion_rel ::= expresion_arit MAYOR expresion_arit 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_rel",17, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion_rel ::= expresion_arit MENOR expresion_arit 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_rel",17, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion_rel ::= expresion_arit 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_rel",17, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion_arit ::= expresion_arit SUMA termino 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_arit",18, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion_arit ::= expresion_arit RESTA termino 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_arit",18, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion_arit ::= termino 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("expresion_arit",18, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // termino ::= termino MULT factor 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // termino ::= termino DIV factor 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // termino ::= termino MOD factor 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // termino ::= factor 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("termino",19, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // factor ::= ID 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // factor ::= NUM_INT 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= NUM_FLOAT 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= CADENA 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= BOOLEAN_LIT 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // factor ::= llamada_metodo 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // factor ::= PARENTESIS_IZQ expresion PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$ParserJava$result = parser.getSymbolFactory().newSymbol("factor",20, ((java_cup.runtime.Symbol)CUP$ParserJava$stack.elementAt(CUP$ParserJava$top-2)), ((java_cup.runtime.Symbol)CUP$ParserJava$stack.peek()), RESULT);
            }
          return CUP$ParserJava$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserJava$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserJava$do_action(
    int                        CUP$ParserJava$act_num,
    java_cup.runtime.lr_parser CUP$ParserJava$parser,
    java.util.Stack            CUP$ParserJava$stack,
    int                        CUP$ParserJava$top)
    throws java.lang.Exception
    {
              return CUP$ParserJava$do_action_part00000000(
                               CUP$ParserJava$act_num,
                               CUP$ParserJava$parser,
                               CUP$ParserJava$stack,
                               CUP$ParserJava$top);
    }
}

}
