
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act8;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOLEAN_LIT = 32;
  public static final int MOD = 23;
  public static final int NUM_INT = 30;
  public static final int MENOR = 27;
  public static final int ELSE = 8;
  public static final int NUM_FLOAT = 31;
  public static final int CADENA = 29;
  public static final int IGUAL = 24;
  public static final int WHILE = 9;
  public static final int SUMA = 19;
  public static final int CONSOLE_LOG = 11;
  public static final int RETURN = 3;
  public static final int FUNCTION = 2;
  public static final int IF = 7;
  public static final int PARENTESIS_IZQ = 12;
  public static final int ID = 28;
  public static final int PARENTESIS_DER = 13;
  public static final int ASIGNAR = 18;
  public static final int COMA = 16;
  public static final int MAYOR = 26;
  public static final int MULT = 21;
  public static final int EOF = 0;
  public static final int DIV = 22;
  public static final int CONST = 6;
  public static final int error = 1;
  public static final int LET = 4;
  public static final int LLAVE_IZQ = 14;
  public static final int PUNTO_COMA = 17;
  public static final int IGUAL_ESTRICTO = 25;
  public static final int LLAVE_DER = 15;
  public static final int FOR = 10;
  public static final int VAR = 5;
  public static final int RESTA = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "RETURN",
  "LET",
  "VAR",
  "CONST",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "CONSOLE_LOG",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "PUNTO_COMA",
  "ASIGNAR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MOD",
  "IGUAL",
  "IGUAL_ESTRICTO",
  "MAYOR",
  "MENOR",
  "ID",
  "CADENA",
  "NUM_INT",
  "NUM_FLOAT",
  "BOOLEAN_LIT"
  };
}

