
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act2_analisis_sintactico;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserSintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserSintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\015\000\002\002\004\000\002\002\003\000\002\003" +
    "\005\000\002\004\005\000\002\004\002\000\002\005\004" +
    "\000\002\005\002\000\002\006\005\000\002\006\007\000" +
    "\002\007\006\000\002\007\007\000\002\010\003\000\002" +
    "\010\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\035\000\012\004\006\005\ufffd\006\ufffd\007\ufffd\001" +
    "\002\000\010\005\ufffb\006\ufffb\007\ufffb\001\002\000\004" +
    "\002\000\001\002\000\004\010\012\001\002\000\004\002" +
    "\010\001\002\000\004\002\001\001\002\000\006\011\014" +
    "\012\013\001\002\000\006\011\ufff6\012\ufff6\001\002\000" +
    "\010\005\ufffe\006\ufffe\007\ufffe\001\002\000\004\010\015" +
    "\001\002\000\006\011\ufff5\012\ufff5\001\002\000\010\005" +
    "\017\006\020\007\022\001\002\000\004\010\012\001\002" +
    "\000\004\010\030\001\002\000\004\002\uffff\001\002\000" +
    "\004\006\024\001\002\000\010\005\ufffc\006\ufffc\007\ufffc" +
    "\001\002\000\004\010\025\001\002\000\004\014\026\001" +
    "\002\000\004\015\027\001\002\000\004\002\ufff7\001\002" +
    "\000\004\014\031\001\002\000\004\015\032\001\002\000" +
    "\004\002\ufff8\001\002\000\006\011\035\012\034\001\002" +
    "\000\010\005\ufffa\006\ufffa\007\ufffa\001\002\000\006\010" +
    "\015\013\036\001\002\000\004\012\037\001\002\000\010" +
    "\005\ufff9\006\ufff9\007\ufff9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\035\000\010\002\006\003\004\004\003\001\001\000" +
    "\004\005\015\001\001\000\002\001\001\000\004\010\010" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\006\022\007\020\001\001\000" +
    "\004\010\032\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserSintactico$actions {
  private final ParserSintactico parser;

  /** Constructor */
  CUP$ParserSintactico$actions(ParserSintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserSintactico$do_action_part00000000(
    int                        CUP$ParserSintactico$act_num,
    java_cup.runtime.lr_parser CUP$ParserSintactico$parser,
    java.util.Stack            CUP$ParserSintactico$stack,
    int                        CUP$ParserSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserSintactico$result;

      /* select the action based on the action number */
      switch (CUP$ParserSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-1)).value;
		RESULT = start_val;
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserSintactico$parser.done_parsing();
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= archivo 
            {
              Object RESULT =null;
		 System.out.println("Regla reconocida: archivo"); 
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // archivo ::= paquete_opcional lista_importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("archivo",1, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // paquete_opcional ::= PACKAGE lista_identificadores SEMICOLON 
            {
              Object RESULT =null;
		int paquetleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)).left;
		int paquetright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)).right;
		Object paquet = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)).value;
		 System.out.println("Regla reconocida: paquete en la línea: " + (paquetleft + 1)); 
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("paquete_opcional",2, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // paquete_opcional ::= 
            {
              Object RESULT =null;

              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("paquete_opcional",2, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_importaciones ::= lista_importaciones importacion 
            {
              Object RESULT =null;

              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("lista_importaciones",3, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // lista_importaciones ::= 
            {
              Object RESULT =null;

              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("lista_importaciones",3, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // importacion ::= IMPORT lista_identificadores SEMICOLON 
            {
              Object RESULT =null;
		int importarleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)).left;
		int importarright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)).right;
		Object importar = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)).value;
		 System.out.println("Regla reconocida: importacion simple en la línea: " + (importarleft + 1)); 
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("importacion",4, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // importacion ::= IMPORT lista_identificadores DOT MULT SEMICOLON 
            {
              Object RESULT =null;
		int importarleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)).left;
		int importarright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)).right;
		Object importar = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)).value;
		 System.out.println("Regla reconocida: importacion multiple en la línea: " + (importarleft + 1)); 
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("importacion",4, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // clase_principal ::= CLASS IDENTIFIER LBRACE RBRACE 
            {
              Object RESULT =null;
		int claseleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)).left;
		int claseright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)).right;
		Object clase = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)).value;
		 System.out.println("Regla reconocida: clase_principal en la línea: " + (claseleft + 1)); 
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("clase_principal",5, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // clase_principal ::= PUBLIC CLASS IDENTIFIER LBRACE RBRACE 
            {
              Object RESULT =null;
		int publicoleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)).left;
		int publicoright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)).right;
		Object publico = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)).value;
		int claseleft = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)).left;
		int claseright = ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)).right;
		Object clase = (Object)((java_cup.runtime.Symbol) CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-3)).value;
		 System.out.println("Regla reconocida: clase_principal publica en la línea: " + (publicoleft + 1)); 
              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("clase_principal",5, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lista_identificadores ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("lista_identificadores",6, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // lista_identificadores ::= lista_identificadores DOT IDENTIFIER 
            {
              Object RESULT =null;

              CUP$ParserSintactico$result = parser.getSymbolFactory().newSymbol("lista_identificadores",6, ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.elementAt(CUP$ParserSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$ParserSintactico$stack.peek()), RESULT);
            }
          return CUP$ParserSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserSintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserSintactico$do_action(
    int                        CUP$ParserSintactico$act_num,
    java_cup.runtime.lr_parser CUP$ParserSintactico$parser,
    java.util.Stack            CUP$ParserSintactico$stack,
    int                        CUP$ParserSintactico$top)
    throws java.lang.Exception
    {
              return CUP$ParserSintactico$do_action_part00000000(
                               CUP$ParserSintactico$act_num,
                               CUP$ParserSintactico$parser,
                               CUP$ParserSintactico$stack,
                               CUP$ParserSintactico$top);
    }
}

}
