
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act2_analisis_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 10;
  public static final int PUBLIC = 5;
  public static final int PACKAGE = 2;
  public static final int MULT = 9;
  public static final int EOF = 0;
  public static final int DOT = 7;
  public static final int error = 1;
  public static final int SEMICOLON = 8;
  public static final int IDENTIFIER = 6;
  public static final int RBRACE = 11;
  public static final int IMPORT = 3;
  public static final int CLASS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PACKAGE",
  "IMPORT",
  "CLASS",
  "PUBLIC",
  "IDENTIFIER",
  "DOT",
  "SEMICOLON",
  "MULT",
  "LBRACE",
  "RBRACE"
  };
}

